[package]
name = "rust-stuff"
version = "0.1.0"
edition = "2021"
include = ["src/*.rs", "src/*.txt"]

[dependencies]
crossbeam = "0.8.4"
jobsys = "0.2.0"
rand = "0.8.5"
rayon = "1.10.0"
tokio = { version = "1.39.1", features = ["full"] }
